/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        bg: "var(--bg)",
        "surface-0": "var(--surface-0)",
        "surface-1": "var(--surface-1)",
        "surface-2": "var(--surface-2)",
        "surface-3": "var(--surface-3)",
        "surface-4": "var(--surface-4)",
        line: "var(--line)",
        "line-strong": "var(--line-strong)",
        "line-glow": "var(--line-glow)",
        "text-hi": "var(--text-hi)",
        "text-mid": "var(--text-mid)",
        "text-lo": "var(--text-lo)",
        "text-dim": "var(--text-dim)",
        indigo: "var(--indigo)",
        "indigo-deep": "var(--indigo-deep)",
        pink: "var(--pink)",
        "pink-deep": "var(--pink-deep)",
        success: "var(--success)",
        warning: "var(--warning)",
        danger: "var(--danger)",
        info: "var(--info)",
        "success-bg": "var(--success-bg)",
        "warning-bg": "var(--warning-bg)",
        "danger-bg": "var(--danger-bg)",
        "info-bg": "var(--info-bg)",
        "accent-bg": "var(--accent-bg)",
      },
      backgroundImage: {
        grad: "var(--grad)",
        "grad-soft": "var(--grad-soft)",
      },
      fontFamily: {
        display: ["Bricolage Grotesque Variable", "system-ui", "sans-serif"],
        ui: ["Space Grotesk Variable", "system-ui", "sans-serif"],
        mono: ["Space Mono", "ui-monospace", "monospace"],
      },
      fontSize: {
        display: ["34px", { lineHeight: "1.1" }],
        h1: ["24px", { lineHeight: "1.2" }],
        h2: ["19px", { lineHeight: "1.3" }],
        h3: ["16px", { lineHeight: "1.4" }],
        body: ["14px", { lineHeight: "1.5" }],
        sm: ["12.5px", { lineHeight: "1.5" }],
        xs: ["11px", { lineHeight: "1.4" }],
        micro: ["9.5px", { lineHeight: "1.3" }],
      },
      borderRadius: {
        sm: "var(--r-sm)",
        md: "var(--r-md)",
        lg: "var(--r-lg)",
        xl: "var(--r-xl)",
        pill: "var(--r-pill)",
      },
      spacing: {
        s1: "var(--s1)",
        s2: "var(--s2)",
        s3: "var(--s3)",
        s4: "var(--s4)",
        s5: "var(--s5)",
        s6: "var(--s6)",
        s7: "var(--s7)",
        s8: "var(--s8)",
        s9: "var(--s9)",
      },
      boxShadow: {
        1: "var(--shadow-1)",
        2: "var(--shadow-2)",
        3: "var(--shadow-3)",
        glow: "var(--glow-accent)",
      },
      keyframes: {
        breathe: {
          "0%, 100%": {
            opacity: "calc(0.55 + 0.1 * var(--motion))",
            transform: "scale(1)",
          },
          "50%": {
            opacity: "1",
            transform: "scale(calc(1 + 0.03 * var(--motion)))",
          },
        },
        "spin-slow": { to: { transform: "rotate(360deg)" } },
        "spin-rev": { to: { transform: "rotate(-360deg)" } },
        shimmer: {
          "0%": { opacity: "0.3" },
          "50%": { opacity: "0.9" },
          "100%": { opacity: "0.3" },
        },
        "float-up": {
          "0%": { transform: "translateY(0) scale(1)", opacity: "0" },
          "15%": { opacity: "1" },
          "100%": { transform: "translateY(-46px) scale(0.4)", opacity: "0" },
        },
        "pulse-ring": {
          "0%": { transform: "scale(0.8)", opacity: "0.7" },
          "100%": { transform: "scale(1.6)", opacity: "0" },
        },
        "dash-flow": { to: { strokeDashoffset: "-28" } },
      },
      animation: {
        breathe: "breathe 3.2s ease-in-out infinite",
        "spin-slow": "spin-slow 24s linear infinite",
        "spin-rev": "spin-rev 32s linear infinite",
        shimmer: "shimmer 1.4s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
